In [2]:
import pandas as pd

In [3]:
def clean_bike_data(df):
    
        # drop duplicates
    df = df.drop_duplicates()
        # drop column 'angelegt_am' and 'erfassungsgrund' - irrelevant to us, when and why observation got added to the database.
    df = df.drop('angelegt_am', axis='columns')
    df = df.drop('erfassungsgrund', axis='columns')
        # we have just 167 attempts and 7 thefts of unknown state in our dataset, so we decide to drop those observations.
    df = df[df['versuch'].isin(['Nein'])]
        # change date text string to datetime datatype

    df['tatzeit_anfang_datum'] = pd.to_datetime(df['tatzeit_anfang_datum'],format='%d.%m.%Y')
    df['tatzeit_ende_datum'] = pd.to_datetime(df['tatzeit_ende_datum'],format='%d.%m.%Y')
    return df

In [5]:
df2020 = pd.read_csv('bike_theft_berlin_2020.csv', encoding='latin-1') 
 # make column names lowercase
df2020.columns = df.columns.str.lower() 
df2020.head(2)

df2020

,angelegt_am,tatzeit_anfang_datum,tatzeit_anfang_stunde,tatzeit_ende_datum,tatzeit_ende_stunde,lor,schadenshoehe,versuch,art_des_fahrrads,delikt,erfassungsgrund
0,29.10.2020,01.01.2020,0,01.01.2020,0,1401046,300,Nein,Fahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von FahrrÃ¤dern
1,02.01.2020,01.01.2020,22,02.01.2020,11,9100408,3676,Nein,diverse FahrrÃ¤der,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von FahrrÃ¤dern
2,04.01.2020,01.01.2020,15,02.01.2020,15,2200211,483,Nein,Damenfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von FahrrÃ¤dern
3,06.01.2020,01.01.2020,15,01.01.2020,20,4501147,999,Nein,Fahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von FahrrÃ¤dern
4,03.01.2020,01.01.2020,1,01.01.2020,12,2400623,264,Nein,Herrenfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von FahrrÃ¤dern
...,...,...,...,...,...,...,...,...,...,...,...
21539,04.01.2021,31.12.2020,12,02.01.2021,14,2300419,217,Nein,Herrenfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von FahrrÃ¤dern
21540,01.01.2021,31.12.2020,11,31.12.2020,23,1400940,600,Nein,Damenfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von FahrrÃ¤dern
21541,31.12.2020,31.12.2020,10,31.12.2020,14,1100103,958,Nein,Herrenfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von FahrrÃ¤dern
21542,04.01.2021,31.12.2020,19,01.01.2021,3,3701555,290,Nein,Herrenfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von FahrrÃ¤dern
21543,01.01.2021,31.12.2020,20,31.12.2020,20,11400930,300,Nein,diverse FahrrÃ¤der,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von FahrrÃ¤dern

In [8]:
cdf2020 = clean_bike_data(df2020)
cdf2020

,tatzeit_anfang_datum,tatzeit_anfang_stunde,tatzeit_ende_datum,tatzeit_ende_stunde,lor,schadenshoehe,versuch,art_des_fahrrads,delikt
0,2020-01-01,0,2020-01-01,0,1401046,300,Nein,Fahrrad,Fahrraddiebstahl
1,2020-01-01,22,2020-01-02,11,9100408,3676,Nein,diverse FahrrÃ¤der,Fahrraddiebstahl
2,2020-01-01,15,2020-01-02,15,2200211,483,Nein,Damenfahrrad,Fahrraddiebstahl
3,2020-01-01,15,2020-01-01,20,4501147,999,Nein,Fahrrad,Fahrraddiebstahl
4,2020-01-01,1,2020-01-01,12,2400623,264,Nein,Herrenfahrrad,Fahrraddiebstahl
...,...,...,...,...,...,...,...,...,...
21539,2020-12-31,12,2021-01-02,14,2300419,217,Nein,Herrenfahrrad,Fahrraddiebstahl
21540,2020-12-31,11,2020-12-31,23,1400940,600,Nein,Damenfahrrad,Fahrraddiebstahl
21541,2020-12-31,10,2020-12-31,14,1100103,958,Nein,Herrenfahrrad,Fahrraddiebstahl
21542,2020-12-31,19,2021-01-01,3,3701555,290,Nein,Herrenfahrrad,Fahrraddiebstahl
21543,2020-12-31,20,2020-12-31,20,11400930,300,Nein,diverse FahrrÃ¤der,Fahrraddiebstahl

In [13]:
df2021 = pd.read_csv('bike_theft_berlin_2021.csv', encoding='latin-1') 
 # make column names lowercase
df2021.columns = df.columns.str.lower() 
df2021.head(2)

cdf2021 = clean_bike_data(df2021)
cdf2021

,tatzeit_anfang_datum,tatzeit_anfang_stunde,tatzeit_ende_datum,tatzeit_ende_stunde,lor,schadenshoehe,versuch,art_des_fahrrads,delikt
0,2021-01-01,17,2021-01-01,18,8401241,888,Nein,Fahrrad,Fahrraddiebstahl
1,2021-01-01,14,2021-01-02,3,10200524,700,Nein,Herrenfahrrad,Fahrraddiebstahl
2,2021-01-01,15,2021-01-03,12,3701555,537,Nein,Herrenfahrrad,Fahrraddiebstahl
3,2021-01-01,1,2021-01-01,23,2300418,500,Nein,Herrenfahrrad,Fahrraddiebstahl
4,2021-01-01,0,2021-01-01,0,9100101,499,Nein,Herrenfahrrad,Fahrraddiebstahl
...,...,...,...,...,...,...,...,...,...
19509,2021-12-31,17,2022-01-02,20,9200818,300,Nein,Kinderfahrrad,Fahrraddiebstahl
19510,2021-12-31,17,2022-01-01,11,2500832,1401,Nein,Herrenfahrrad,Fahrraddiebstahl
19511,2021-12-31,14,2022-01-01,17,8100206,402,Nein,Herrenfahrrad,Fahrraddiebstahl
19512,2021-12-31,12,2021-12-31,12,1300834,1800,Nein,Fahrrad,Fahrraddiebstahl
19513,2021-12-31,15,2022-01-01,12,1100205,550,Nein,Damenfahrrad,Fahrraddiebstahl

In [14]:
df2022 = pd.read_csv('bike_theft_berlin_2022.csv', encoding='latin-1') 
 # make column names lowercase
df2022.columns = df.columns.str.lower() 

cdf2022 = clean_bike_data(df2022)
cdf2022

,tatzeit_anfang_datum,tatzeit_anfang_stunde,tatzeit_ende_datum,tatzeit_ende_stunde,lor,schadenshoehe,versuch,art_des_fahrrads,delikt
0,2022-01-01,16,2022-01-01,19,2400623,1754,Nein,Herrenfahrrad,Fahrraddiebstahl
1,2022-01-01,12,2022-01-03,15,8100103,1093,Nein,Fahrrad,Fahrraddiebstahl
2,2022-01-01,3,2022-01-02,17,3500934,1259,Nein,Damenfahrrad,Fahrraddiebstahl
3,2022-01-01,0,2022-01-01,0,4501152,400,Nein,Kinderfahrrad,Fahrraddiebstahl
4,2022-01-01,13,2022-01-03,10,4501043,1109,Nein,diverse FahrrÃ¤der,Fahrraddiebstahl
...,...,...,...,...,...,...,...,...,...
22611,2022-12-31,21,2023-01-01,15,7601546,400,Nein,Fahrrad,Fahrraddiebstahl
22612,2022-12-31,15,2023-01-01,19,2200212,520,Nein,Rennrad,Fahrraddiebstahl
22613,2022-12-31,12,2022-12-31,21,3300412,527,Nein,diverse FahrrÃ¤der,Fahrraddiebstahl
22614,2022-12-31,18,2022-12-31,20,1100102,899,Nein,Herrenfahrrad,Fahrraddiebstahl
22615,2022-12-31,18,2022-12-31,20,1100102,1034,Nein,Herrenfahrrad,Fahrraddiebstahl

In [15]:
df2023 = pd.read_csv('bike_theft_berlin_2023.csv', encoding='latin-1') 
 # make column names lowercase
df2023.columns = df.columns.str.lower() 

cdf2023 = clean_bike_data(df2023)
cdf2023

,tatzeit_anfang_datum,tatzeit_anfang_stunde,tatzeit_ende_datum,tatzeit_ende_stunde,lor,schadenshoehe,versuch,art_des_fahrrads,delikt
0,2023-01-01,6,2023-01-01,12,4300621,400,Nein,Fahrrad,Fahrraddiebstahl
1,2023-01-01,23,2023-01-02,9,9300921,2849,Nein,Herrenfahrrad,Fahrraddiebstahl
2,2023-01-01,12,2023-01-01,18,6300526,695,Nein,Damenfahrrad,Fahrraddiebstahl
3,2023-01-01,12,2023-01-02,12,9100101,2000,Nein,Herrenfahrrad,Fahrraddiebstahl
4,2023-01-01,0,2023-01-01,23,4400728,400,Nein,Herrenfahrrad,Fahrraddiebstahl
...,...,...,...,...,...,...,...,...,...
31110,2024-06-19,15,2024-06-19,22,6400735,781,Nein,Herrenfahrrad,Fahrraddiebstahl
31111,2024-06-19,9,2024-06-19,9,8100206,400,Nein,Fahrrad,Fahrraddiebstahl
31113,2024-06-19,16,2024-06-19,16,2500729,1850,Nein,Herrenfahrrad,Fahrraddiebstahl
31114,2024-06-19,7,2024-06-19,18,6300526,1860,Nein,Fahrrad,Fahrraddiebstahl
31115,2024-06-19,8,2024-06-19,15,6100209,430,Nein,Damenfahrrad,Fahrraddiebstahl

In [17]:
completelist = pd.concat([cdf2020,cdf2021,cdf2022,cdf2023], ignore_index=True)
completelist

,tatzeit_anfang_datum,tatzeit_anfang_stunde,tatzeit_ende_datum,tatzeit_ende_stunde,lor,schadenshoehe,versuch,art_des_fahrrads,delikt
0,2020-01-01,0,2020-01-01,0,1401046,300,Nein,Fahrrad,Fahrraddiebstahl
1,2020-01-01,22,2020-01-02,11,9100408,3676,Nein,diverse FahrrÃ¤der,Fahrraddiebstahl
2,2020-01-01,15,2020-01-02,15,2200211,483,Nein,Damenfahrrad,Fahrraddiebstahl
3,2020-01-01,15,2020-01-01,20,4501147,999,Nein,Fahrrad,Fahrraddiebstahl
4,2020-01-01,1,2020-01-01,12,2400623,264,Nein,Herrenfahrrad,Fahrraddiebstahl
...,...,...,...,...,...,...,...,...,...
94206,2024-06-19,15,2024-06-19,22,6400735,781,Nein,Herrenfahrrad,Fahrraddiebstahl
94207,2024-06-19,9,2024-06-19,9,8100206,400,Nein,Fahrrad,Fahrraddiebstahl
94208,2024-06-19,16,2024-06-19,16,2500729,1850,Nein,Herrenfahrrad,Fahrraddiebstahl
94209,2024-06-19,7,2024-06-19,18,6300526,1860,Nein,Fahrrad,Fahrraddiebstahl
94210,2024-06-19,8,2024-06-19,15,6100209,430,Nein,Damenfahrrad,Fahrraddiebstahl

In [23]:
original_lor = pd.read_excel('broker.xls') 
original_lor

,Planungsraum (Nummer),Planungsraum (Name),Bezirksregion (Nummer),Bezirksregion (Name),Prognoseraum (Nummer),Prognoseraum (Name),Bezirk,Fläche in qm,Zuordnung zum Stadtraum (Zahl),Zuordnung zum Stadtraum,Stand der Daten
0,1100101,Stülerstraße,11001,Tiergarten Süd,110,Zentrum,01 - Mitte,3.669331e+05,1,Innere Stadt,01.01.2021
1,1100102,Großer Tiergarten,11001,Tiergarten Süd,110,Zentrum,01 - Mitte,3.919852e+06,1,Innere Stadt,01.12.2021
2,1100103,Lützowstraße,11001,Tiergarten Süd,110,Zentrum,01 - Mitte,5.471832e+05,1,Innere Stadt,01.12.2021
3,1100104,Körnerstraße,11001,Tiergarten Süd,110,Zentrum,01 - Mitte,3.385139e+05,1,Innere Stadt,01.12.2021
4,1100205,Wilhelmstraße,11002,Regierungsviertel,110,Zentrum,01 - Mitte,6.346568e+05,1,Innere Stadt,01.01.2021
...,...,...,...,...,...,...,...,...,...,...,...
537,12601032,Rollbergesiedlung,126010,Rollbergesiedlung,1260,Märkisches Viertel,12 - Reinickendorf,5.013250e+05,2,Äußere Stadt,01.01.2021
538,12601133,Treuenbrietzener Straße,126011,MV Nord,1260,Märkisches Viertel,12 - Reinickendorf,9.183440e+05,2,Äußere Stadt,01.01.2021
539,12601134,Märkisches Zentrum,126011,MV Nord,1260,Märkisches Viertel,12 - Reinickendorf,1.127871e+06,2,Äußere Stadt,01.01.2021
540,12601235,Dannenwalder Weg,126012,MV Süd,1260,Märkisches Viertel,12 - Reinickendorf,5.234426e+05,2,Äußere Stadt,01.01.2021
541,12601236,Schorfheidestraße,126012,MV Süd,1260,Märkisches Viertel,12 - Reinickendorf,5.782850e+05,2,Äußere Stadt,01.01.2021

In [32]:
small_lor = original_lor[['Planungsraum (Nummer)','Bezirk','Bezirksregion (Name)','Planungsraum (Name)']]
small_lor.rename(columns={'Planungsraum (Nummer)':'lor'}, inplace=True)
small_lor

/var/folders/38/42l25rn57sx4__jwn4b4_k480000gn/T/ipykernel_71278/4113707206.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  small_lor.rename(columns={'Planungsraum (Nummer)':'lor'}, inplace=True)

,lor,Bezirk,Bezirksregion (Name),Planungsraum (Name)
0,1100101,01 - Mitte,Tiergarten Süd,Stülerstraße
1,1100102,01 - Mitte,Tiergarten Süd,Großer Tiergarten
2,1100103,01 - Mitte,Tiergarten Süd,Lützowstraße
3,1100104,01 - Mitte,Tiergarten Süd,Körnerstraße
4,1100205,01 - Mitte,Regierungsviertel,Wilhelmstraße
...,...,...,...,...
537,12601032,12 - Reinickendorf,Rollbergesiedlung,Rollbergesiedlung
538,12601133,12 - Reinickendorf,MV Nord,Treuenbrietzener Straße
539,12601134,12 - Reinickendorf,MV Nord,Märkisches Zentrum
540,12601235,12 - Reinickendorf,MV Süd,Dannenwalder Weg
541,12601236,12 - Reinickendorf,MV Süd,Schorfheidestraße

In [35]:
finish_list = pd.merge(left= completelist,right= small_lor,how='left',on='lor')
finish_list

,tatzeit_anfang_datum,tatzeit_anfang_stunde,tatzeit_ende_datum,tatzeit_ende_stunde,lor,schadenshoehe,versuch,art_des_fahrrads,delikt,Bezirk,Bezirksregion (Name),Planungsraum (Name)
0,2020-01-01,0,2020-01-01,0,1401046,300,Nein,Fahrrad,Fahrraddiebstahl,01 - Mitte,Wedding Zentrum,Nordufer
1,2020-01-01,22,2020-01-02,11,9100408,3676,Nein,diverse FahrrÃ¤der,Fahrraddiebstahl,09 - Treptow-Köpenick,Johannisthal,Johannisthal Ost
2,2020-01-01,15,2020-01-02,15,2200211,483,Nein,Damenfahrrad,Fahrraddiebstahl,02 - Friedrichshain-Kreuzberg,Tempelhofer Vorstadt,Chamissokiez
3,2020-01-01,15,2020-01-01,20,4501147,999,Nein,Fahrrad,Fahrraddiebstahl,04 - Charlottenburg-Wilmersdorf,Volkspark Wilmersdorf,Leon-Jessel-Platz
4,2020-01-01,1,2020-01-01,12,2400623,264,Nein,Herrenfahrrad,Fahrraddiebstahl,02 - Friedrichshain-Kreuzberg,Karl-Marx-Allee Süd,Andreasviertel
...,...,...,...,...,...,...,...,...,...,...,...,...
94206,2024-06-19,15,2024-06-19,22,6400735,781,Nein,Herrenfahrrad,Fahrraddiebstahl,06 - Steglitz-Zehlendorf,Zehlendorf Südwest,Wannsee
94207,2024-06-19,9,2024-06-19,9,8100206,400,Nein,Fahrrad,Fahrraddiebstahl,08 - Neukölln,Neuköllner Mitte/Zentrum,Flughafenstraße
94208,2024-06-19,16,2024-06-19,16,2500729,1850,Nein,Herrenfahrrad,Fahrraddiebstahl,02 - Friedrichshain-Kreuzberg,Frankfurter Allee Nord,Pettenkofer Straße
94209,2024-06-19,7,2024-06-19,18,6300526,1860,Nein,Fahrrad,Fahrraddiebstahl,06 - Steglitz-Zehlendorf,Teltower Damm,Zehlendorf Mitte
94210,2024-06-19,8,2024-06-19,15,6100209,430,Nein,Damenfahrrad,Fahrraddiebstahl,06 - Steglitz-Zehlendorf,Albrechtstraße,Feuerbachstraße

In [37]:
finish_list.to_csv("finish_list.csv")